# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d67cd05154dc046450a66e97eea6d9499e90388fec347d989840479bee58f1ffae5ddbd3aabcaab20b403214bcd68e7b9758a72ddfb1f50b10b914b6c5e2114f

test:
  secret_key_base: 7774da470480186c92dacc9671ed5c3ab00b165bc500b7adc23c236500f4d25622c9d32368ed413b4e1764a7044e33462fc71415383ae7e3d0433e6db168c91f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
